### ISSUE TITLE
Unable to pack/depack this file

### ISSUE THREAD

**Issue by charlierobson** [abekermsx/BitBuster-1.2#1]
Hi.

I'm having a bad time with a particular bin file. I packed it and tested the unpacking with the windows binaries. All good 👍 Unpacking to memory using the supplied z80 depack routine though - not so good. The depack routine is running from ROM if that matters. I know some decrunchers self modify but looking at the code this doesn't seem to be the case.

Attached is a zip with the original file and a packed version. Also attached a memory dump of the failed decompaction.

Any help working out what is going on would be greatly appreciated.

[bug.zip](https://github.com/abekermsx/BitBuster-1.2/files/9759421/bug.zip)
[memdump.zip](https://github.com/abekermsx/BitBuster-1.2/files/9759429/memdump.zip)

Thanks
Charlie

**Comment by charlierobson** [comment]
Update:

User error. Well, emulator error actually but I feel pretty stupid. Please close and or delete with extreme prejudice :D

**Comment by abekermsx** [comment]
Don't worry about it, thanks for using BitBuster :)
